# Generated by Django 5.2.4 on 2026-02-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('discounted_price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('best_seller', 'Best Seller'), ('none', 'None')], default='new', max_length=20)),
                ('type', models.CharField(choices=[('face', 'Face'), ('body', 'Body'), ('hair', 'Hair')], default='face', max_length=20)),
                ('image', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Lenature.category')),
            ],
        ),
    ]
