# Generated by Django 5.1.5 on 2025-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenature', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(),
        ),
    ]
