# Generated by Django 5.1.5 on 2025-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenature', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('best_seller', 'Best Seller'), ('none', 'None')], default='new', max_length=20),
        ),
    ]
