# Generated by Django 5.1.5 on 2025-03-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenature', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('face', 'Face'), ('body', 'Body'), ('hair', 'Hair')], default='face', max_length=20),
        ),
    ]
