# Generated by Django 5.1.5 on 2025-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lenature', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
